### ISSUE TITLE
Uploading package to melpa

### ISSUE THREAD

**Issue by Gonzih** [ALSchwalm/flycheck-nim#1]
Hi,

Is there any chance that this package could become available via melpa?
I'm working on a configuration layer for spacemacs and it's much simpler to load external dependencies from repository and not a local path.

Cheers!

**Comment by ALSchwalm** [comment]
Sorry for the late reply, I didn't see this opened. I originally held off on uploading this anywhere because I was told by some nim devs that the format of the output was not yet stable. It doesn't seem likes its changed in the ~7 months since I wrote this though, so I'll see about getting it added to melpa.

**Comment by Gonzih** [comment]
Thanks, let me know once it's there so I can remove inlined dependency from my spacemacs configuration layer.

Thanks!

**Comment by ALSchwalm** [comment]
This package is now available in melpa under the name `flycheck-nim`. Thanks for opening the issue, I would probably never have gotten around to it otherwise.

**Comment by Gonzih** [comment]
No problem! Now I need to integrate it in to the spacemacs. Cheers!

**Comment by Gonzih** [comment]
Now package is used in spacemacs, thanks!

On 12 September 2015 at 19:40, Adam Schwalm notifications@github.com
wrote:

> This package is now available in melpa under the name flycheck-nim.
> Thanks for opening the issue, I would probably never have gotten around to
> it otherwise.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ALSchwalm/flycheck-nim/issues/1#issuecomment-139799540
> .

## 

Regards,
Max
